=== gemini-hlsw/acm/src/main/resources/CaSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.gemini.edu/CaSchema" xmlns:tns="http://www.gemini.edu/CaSchema"
	elementFormDefault="qualified">


	<xs:element name="Records">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Top" type="tns:TopType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="Apply" type="tns:ApplyType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="Status" type="tns:StatusType"
					minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="TopType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="DataType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="INTEGER" />
			<xs:enumeration value="STRING" />
			<xs:enumeration value="DOUBLE" />
			<xs:enumeration value="FLOAT" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="StatusType">
		<xs:sequence>
			<xs:element name="top" type="xs:string" />
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="attribute" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="channel" type="xs:string" />
						<xs:element name="type" type="tns:DataType" />
						<xs:element name="description" type="xs:string"
							minOccurs="0" />
						<xs:element name="top" type="xs:string" maxOccurs="1"
							minOccurs="0" />
					</xs:sequence>
					<xs:attribute name="name" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="ApplyType">
		<xs:sequence>
			<xs:element name="top" type="xs:string" />
			<xs:element name="apply" type="xs:string" />
			<xs:element name="car" type="xs:string" />
			<xs:element name="gem5" type="xs:boolean" minOccurs="0" />
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="command" type="tns:CommandType"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="CommandType">
		<xs:sequence>
			<xs:element name="record" type="xs:string" default=""
				minOccurs="0" />
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="channel" type="xs:string" />
						<xs:element name="type" type="tns:DataType" />
						<xs:element name="description" type="xs:string"
							minOccurs="0" />
						<xs:element name="isCAD" type="xs:boolean" default="true"
							minOccurs="0" />
					</xs:sequence>
					<xs:attribute name="name" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>

</xs:schema>

=== gemini-hlsw/acm/src/test/resources/TestConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Records xmlns:tns="http://www.gemini.edu/CaSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.gemini.edu/CaSchema ../../main/resources/CaSchema.xsd">
	<tns:Top name="test">test</tns:Top>
	<tns:Apply name="testApply">
		<tns:top>test</tns:top>
		<tns:apply>apply</tns:apply>
		<tns:car>applyC</tns:car>
		<tns:description>Test apply record</tns:description>
		<tns:command name="test">
			<tns:description>Basic test command</tns:description>
			<tns:parameter name="param1">
				<tns:channel>test.param1</tns:channel>
				<tns:type>STRING</tns:type>
				<tns:description>First parameter</tns:description>
			</tns:parameter>
			<tns:parameter name="param2">
				<tns:channel>test.param2</tns:channel>
				<tns:type>STRING</tns:type>
				<tns:description>Second parameter</tns:description>
			</tns:parameter>
		</tns:command>
		<tns:command name="reboot">
			<tns:record>reboot</tns:record>
			<tns:description>Reboot command</tns:description>
		</tns:command>
		<tns:command name="init">
			<tns:record>init</tns:record>
			<tns:description>Init command</tns:description>
		</tns:command>
	</tns:Apply>
	<tns:Status name="testStatus">
		<tns:top>test</tns:top>
		<tns:description>Test status</tns:description>
		<tns:attribute name="intStatus">
			<tns:channel>intVal</tns:channel>
			<tns:type>INTEGER</tns:type>
			<tns:description>Integer status</tns:description>
		</tns:attribute>
		<tns:attribute name="strStatus">
			<tns:channel>strVal</tns:channel>
			<tns:type>STRING</tns:type>
			<tns:description>String status</tns:description>
		</tns:attribute>
		<tns:attribute name="dblStatus">
			<tns:channel>dblVal</tns:channel>
			<tns:type>DOUBLE</tns:type>
			<tns:description>Double status</tns:description>
		</tns:attribute>
		<tns:attribute name="fltStatus">
			<tns:channel>fltVal</tns:channel>
			<tns:type>FLOAT</tns:type>
			<tns:description>Float status</tns:description>
		</tns:attribute>
	</tns:Status>
</tns:Records>
